### ISSUE TITLE
Error line 7 on inc/posts.php -- remove <?php

### ISSUE THREAD

**Issue by memartinez** [M27Mangan/manganite#24]
<?php
/**
 * Declaring post types
 *
 * @package masondigital
 */

/**
 * Declaring post types
 *
 * @package masondigital
 */
 // Register Custom Post Type
 function news_post_type() {
 
 	$labels = array(
 		'name'                  => _x( 'News Articles', 'Post Type General Name', 'masondigital' ),
 		'singular_name'         => _x( 'News Article', 'Post Type Singular Name', 'masondigital' ),
 		'menu_name'             => __( 'News', 'masondigital' ),
 		'name_admin_bar'        => __( 'News', 'masondigital' ),
 		'archives'              => __( 'News Archives', 'masondigital' ),
 		'attributes'            => __( 'News Attributes', 'masondigital' ),
 		'parent_item_colon'     => __( 'Parent Item:', 'masondigital' ),
 		'all_items'             => __( 'All Items', 'masondigital' ),
 		'add_new_item'          => __( 'Add New Item', 'masondigital' ),
 		'add_new'               => __( 'Add New', 'masondigital' ),
 		'new_item'              => __( 'New Item', 'masondigital' ),
 		'edit_item'             => __( 'Edit Item', 'masondigital' ),
 		'update_item'           => __( 'Update Item', 'masondigital' ),
 		'view_item'             => __( 'View Item', 'masondigital' ),
 		'view_items'            => __( 'View Items', 'masondigital' ),
 		'search_items'          => __( 'Search Item', 'masondigital' ),
 		'not_found'             => __( 'Not found', 'masondigital' ),
 		'not_found_in_trash'    => __( 'Not found in Trash', 'masondigital' ),
 		'featured_image'        => __( 'Featured Image', 'masondigital' ),
 		'set_featured_image'    => __( 'Set featured image', 'masondigital' ),
 		'remove_featured_image' => __( 'Remove featured image', 'masondigital' ),
 		'use_featured_image'    => __( 'Use as featured image', 'masondigital' ),
 		'insert_into_item'      => __( 'Insert into item', 'masondigital' ),
 		'uploaded_to_this_item' => __( 'Uploaded to this item', 'masondigital' ),
 		'items_list'            => __( 'Items list', 'masondigital' ),
 		'items_list_navigation' => __( 'Items list navigation', 'masondigital' ),
 		'filter_items_list'     => __( 'Filter items list', 'masondigital' ),
 	);
 	$args = array(
 		'label'                 => __( 'News Article', 'masondigital' ),
 		'description'           => __( 'News for Rosina Corporate', 'masondigital' ),
 		'labels'                => $labels,
 		'supports'              => array( 'title', 'editor', 'thumbnail', 'custom-fields', ),
 		'taxonomies'            => array( 'category', 'post_tag' ),
 		'hierarchical'          => false,
 		'public'                => true,
 		'show_ui'               => true,
 		'show_in_menu'          => true,
 		'menu_position'         => 5,
 		'show_in_admin_bar'     => true,
 		'show_in_nav_menus'     => true,
 		'can_export'            => true,
 		'has_archive'           => true,
 		'exclude_from_search'   => false,
 		'publicly_queryable'    => true,
 		'capability_type'       => 'page',
 	);
 	register_post_type( 'news', $args );
 
 }
 add_action( 'init', 'news_post_type', 0 );

**Comment by M27Mangan** [comment]
fixed finally
